// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDMscrOKkNB6pb-gOeagQCYnsaErTY07k',
    appId: '1:360628935119:web:f423a1303072ce236c5aba',
    messagingSenderId: '360628935119',
    projectId: 'flowerapp-6ae0c',
    authDomain: 'flowerapp-6ae0c.firebaseapp.com',
    storageBucket: 'flowerapp-6ae0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7_CSO1cT-lk2VTzBlyzqCkh9LkY3n3tg',
    appId: '1:360628935119:android:1111f61e2c1a1df06c5aba',
    messagingSenderId: '360628935119',
    projectId: 'flowerapp-6ae0c',
    storageBucket: 'flowerapp-6ae0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvRJwHYrmKfi5RQATpX3Z0ep0d8k94yMg',
    appId: '1:360628935119:ios:c568f6ced325c44d6c5aba',
    messagingSenderId: '360628935119',
    projectId: 'flowerapp-6ae0c',
    storageBucket: 'flowerapp-6ae0c.appspot.com',
    iosBundleId: 'com.example.deneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvRJwHYrmKfi5RQATpX3Z0ep0d8k94yMg',
    appId: '1:360628935119:ios:fd1073ce199d6d516c5aba',
    messagingSenderId: '360628935119',
    projectId: 'flowerapp-6ae0c',
    storageBucket: 'flowerapp-6ae0c.appspot.com',
    iosBundleId: 'com.example.deneme.RunnerTests',
  );
}
